backend:
  name: git-gateway
  branch: main   # hvis din standard-branch hedder noget andet, ret her

publish_mode: editorial_workflow

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "produkter"
    label: "Produkter"
    folder: "content/produkter"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Kategori", name: "category", widget: "string", required: false }
      - { label: "Pris (dag)", name: "price_day", widget: "number", required: false }
      - { label: "Pris (weekend)", name: "price_weekend", widget: "number", required: false }
      - { label: "Billede", name: "image", widget: "image", required: false }
      - { label: "Beskrivelse", name: "body", widget: "markdown", required: false }
